@echo off
cd /d %~dp0
if exist "__backups_dialogue_save__" rmdir /s /q "__backups_dialogue_save__"
if exist "core/__pycache__" rmdir /s /q "core/__pycache__"
if exist "core/__pycache__/__init__.cpython-312.pyc" del /q "core/__pycache__/__init__.cpython-312.pyc"
if exist "core/__pycache__/assets.cpython-312.pyc" del /q "core/__pycache__/assets.cpython-312.pyc"
if exist "core/__pycache__/camera.cpython-312.pyc" del /q "core/__pycache__/camera.cpython-312.pyc"
if exist "core/__pycache__/config.cpython-312.pyc" del /q "core/__pycache__/config.cpython-312.pyc"
if exist "core/__pycache__/grid.cpython-312.pyc" del /q "core/__pycache__/grid.cpython-312.pyc"
if exist "core/__pycache__/models.cpython-312.pyc" del /q "core/__pycache__/models.cpython-312.pyc"
if exist "core/__pycache__/npc.cpython-312.pyc" del /q "core/__pycache__/npc.cpython-312.pyc"
if exist "core/__pycache__/player.cpython-312.pyc" del /q "core/__pycache__/player.cpython-312.pyc"
if exist "core/__pycache__/tilemap.cpython-312.pyc" del /q "core/__pycache__/tilemap.cpython-312.pyc"
if exist "core/__pycache__/ui.cpython-312.pyc" del /q "core/__pycache__/ui.cpython-312.pyc"
if exist "core/assets.py.bak_before_pathfix" del /q "core/assets.py.bak_before_pathfix"
if exist "core/ui.py.bak_before_pathfix" del /q "core/ui.py.bak_before_pathfix"
if exist "data/dialogues/peer_stage1.json.bak_pre_unify" del /q "data/dialogues/peer_stage1.json.bak_pre_unify"
if exist "data/dialogues/teacher_intro.json.bak_pre_unify" del /q "data/dialogues/teacher_intro.json.bak_pre_unify"
if exist "main.py.bak_before_dialogue_save_patch" del /q "main.py.bak_before_dialogue_save_patch"
if exist "scenes/__pycache__" rmdir /s /q "scenes/__pycache__"
if exist "scenes/__pycache__/__init__.cpython-312.pyc" del /q "scenes/__pycache__/__init__.cpython-312.pyc"
if exist "scenes/__pycache__/battle_grid.cpython-312.pyc" del /q "scenes/__pycache__/battle_grid.cpython-312.pyc"
if exist "scenes/__pycache__/campus.cpython-312.pyc" del /q "scenes/__pycache__/campus.cpython-312.pyc"
if exist "scenes/__pycache__/menu.cpython-312.pyc" del /q "scenes/__pycache__/menu.cpython-312.pyc"
if exist "scenes/__pycache__/mind_hub.cpython-312.pyc" del /q "scenes/__pycache__/mind_hub.cpython-312.pyc"
if exist "scenes/__pycache__/story_scene.cpython-312.pyc" del /q "scenes/__pycache__/story_scene.cpython-312.pyc"
if exist "scenes/__pycache__/world_places.cpython-312.pyc" del /q "scenes/__pycache__/world_places.cpython-312.pyc"
if exist "scenes/battle_grid.py (2).bak" del /q "scenes/battle_grid.py (2).bak"
if exist "scenes/battle_grid.py.bak_before_dialogue_unify" del /q "scenes/battle_grid.py.bak_before_dialogue_unify"
if exist "scenes/campus.py.bak_before_dialogue_unify" del /q "scenes/campus.py.bak_before_dialogue_unify"
if exist "scenes/menu.py.bak_before_dialogue_unify" del /q "scenes/menu.py.bak_before_dialogue_unify"
if exist "scenes/mind_hub.py.bak_before_dialogue_unify" del /q "scenes/mind_hub.py.bak_before_dialogue_unify"
if exist "scenes/story_scene.py.bak_before_dialogue_unify" del /q "scenes/story_scene.py.bak_before_dialogue_unify"
if exist "scenes/world_places.py.bak_before_dialogue_unify" del /q "scenes/world_places.py.bak_before_dialogue_unify"